server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
  #  servlet:
  #    context-path: /${spring.application.name}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain

spring:
  application:
    name: dows-oss
  profiles:
    include: mysql,apidoc,mybatis,caffeine,rade,feign,oss,mineru
    active: sit

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    root: info

wx:
  pay:
    merchant-id: 1900006XXX          # 替换为实际商户号
    app-id: wxd678efh567hg6787       # 替换为实际APPID
    private-key-path: classpath:/cert/apiclient_key.pem  # 私钥文件路径
    merchant-serial-number: 5157F09EFDC096DE15EBE81A47057A7232F1B8E1  # 证书序列号
    api-v3-key: your-api-v3-key-here  # 替换为实际APIv3密钥
    notify-url: https://your-domain.com/api/pay/notify  # 回调通知地址
    return-url: https://your-domain.com/pay/success     # 支付成功跳转地址
ali:
  pay:
    app-id: 9021000157611719
    productCode: FACE_TO_FACE_PAYMENT
    public-key:
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6N7+azBWGP7/yMJey3lphsmP8GjW3RFQrOvuV3CQFYld/EbRrvwQEkyIPAxYA3H1+WgctGwu5CbmcKTPbXlYpDcnzNGh2akn0cITaFOFQwQuzHCe4k93rIJtrNDgwgTD9zFrLKoIKUQ0DOhQfTA88kY3cdgSkKJoEqdkNDwCgPeN/2H9I08w2ZKboEpMzrtLEQgHPsIBa7ZwM9KrHd9IpSGYr8iD6+HzpWVROb7QuH8FutYKDT/ekBE17RR+vCalFs0Xa67JuD8zuyrjW4jNqoOcb6jN4n7VOlcoKtAewUmPWYrjWz3aqFclHwQSxCHGMFhQakl1SC5t3bobn8/BDAgMBAAECggEAZ34qP9bis4zkma6F8MQBCUECro7Ggcc43BnYzw3c+x0PsbBeTG+JxR0clalKZkokeL+CM4BPgJQ2EuMXTfjc+84NCdx7niwuU+rg+u8V1jKj1PR14vBTKqUhm3AXNmXmm3cikr1aLm+jQsLZghdcdHYUmI0CwVVLXAIlfktzNpqbuB4d2rq6i13txWTrEqOLemhZXcPVBmKtIgfChR9z3pv2QMPNMBUKyzp2iK9tb+1Duw1FC9mlE4GpqeCUmHZMe6TST9HLH4vH2joui6RxXJkMFbZQYuLHgU0/+TeiF0VDHN+AUowjwncLe6DmzzvQ6gMI9TNXoW2bXbV9scMuMQKBgQDmNCVKYPWE0CY5HyKmnjkNNfAfq7G0A1Z1xqiuTJvcfFL2h8VSkSDLv+Vx2vM2+apzRzB6ZKZKmNgz9ZB584o5eCW88UMbEx7W3cv4a5z07ELR8NuoHTL7jloGuaNqIHFZmY6V4lRopZ9vfRUEvwfV07jSotVQpf9/jwvN0vaMiQKBgQDPFcdAkTA6xoY5acCHC7tTPowb+HPC6lWHDWw45BORxY9MbFxyLAEDfDKcwVWicIaupZOGGvJmj349qownGWK2JuBS+nS8NBL9kqLTv6tKj7JtXvBHYgJfzJzGmH+iyrvD2JHHYxQMr05aDdVxpRPqI35RcSEqPiBjRCMTq77bawKBgQDCuSFCBTopGhj7AIdDAVuo/RMc9xLd/mTIQz60EUFWBCP5PWeALBrdvnjLEjXhLtcro/Ax16mCOD/J09JeFc+6RRNG+52T7VyMzBiZDg46bw8mnuJvFiPl/cfRIH5GayL2c5nU1xonWtG+cMOyvBRYnzsbkXl3OrMgp1OIywaaYQKBgGL4y6QGQAC3RQtHiaaBauQcLqZnlhwAFyRWu/RsvRWcUCJ8X6qJcWqS/zWACUd7dEMgC2O6mUN/LRyX2CgPr+fSqL+/x+7zDGh4nq2JG3qlNueiyj+zjeLvTbZ0x/ur3RV6+iFLLxfo6Q+NMQgBl4T9ta+C3BDuZFhNBl6uZKdFAoGAE8y1/3FNJLfEw3V/6YsHz6x4sfEQrixNv0mYV1wye8Le26GUVVvk9JLldQ7Spn9NkdFJS8dDXtgDRFg3kk7xoEhoy8+kXLs2Mba+BEFmh+pzAdgdx9r807hgIdMTbi/eYQU668OsE713FhkkJVzNfULxB9tYzSdbeYpbmluMD8A=
    cert-path: classpath:/cert/ali/test/appPublicCert.crt
    ali-pay-public-cert-path: classpath:/cert/ali/test/alipayPublicCert.crt
    root-cert-path: classpath:/cert/ali/test/alipayRootCert.crt
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    notify-url: https://dev.bole.hioas.com/api/v1/ali/pay/notify  # 回调通知地址
    return-url: https://your-domain.com/pay/success     # 支付成功跳转地址

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 18001
orgImgPath: /applications/resources/img/org/

rade:
  cacheName: hrm
  encryptor:
    enable: true
    algorithm: AES
    secretKey: 3fb2uPksjNOnxZI3


---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
server:
  port: 28002
orgImgPath: /applications/resources/img/org/

---
#测试环境
spring:
  config:
    activate:
      on-profile: uat
server:
  port: 38001

---
#测试环境
spring:
  config:
    activate:
      on-profile: prd
server:
  port: 48001