server:
  port: 8080

spring:
  application:
    name: member-app
  datasource:
    url: jdbc:mysql://localhost:3306/dows_member?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-flex:
  datasource:
    sql-print: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html